name: Check Conventional Commits
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          fetch-depth: ${{ github.event.pull_request.commits }}
          fetch-tags: true
      - name: Conventional commit check
        uses: cocogitto/cocogitto-action@v3