name: Check Conventional Commits
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          fetch-depth: ${{ github.event.pull_request.commits }}
          fetch-tags: true
      - name: Conventional commit check
        uses: cocogitto/cocogitto-action@v3
  visual-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Storybook branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ci/Storybook-visual-tests-in-pipeline

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dependencies
        run: |
          npm ci
          npm install -g backstopjs

      - name: Start Storybook server
        run: |
          npm run storybook:dev &
          echo $! > storybook.pid
          echo "Waiting for Storybook to be ready..."
          npx wait-on http://localhost:6006/iframe.html
          echo "Storybook is ready."

      - name: Generate Reference Screenshots
        run: npm run backstop:reference

      - name: Stop Storybook server
        run: kill $(cat storybook.pid)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backstop-reference
          path: backstop_data/bitmaps_reference

      - name: Checkout Pull Request
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Download artifact on new branch
        uses: actions/download-artifact@v4
        with:
          name: backstop-reference
          path: backstop_data/bitmaps_reference
          
      - name: Install dependencies
        run: |
          npm ci
          npm install -g backstopjs

      - name: Start Storybook server
        run: |
          ls
          npm run storybook:dev &
          echo "Waiting for Storybook to be ready..."
          npx wait-on http://localhost:6006/iframe.html
          echo "Storybook is ready."

      - name: Run Visual Tests
        run: npm run backstop:test

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backstop-report
          path: backstop_data
