name: Build React Library
on:
  push:
    branches: [ main, Storybook ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: |
          npm run generate:css
          ls -al
          npm run build
          # Create .gitignore file excluding dist folder
          echo -e "\n!dist\n!dist/*" >> .gitignore

      - name: Commit built files
        run: |
          cat .gitignore
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Add dist folder contents
          git add dist/
          
          # Only commit if there are changes
          if git diff --cached --quiet ; then
            echo "No changes in dist folder"
          else
            git commit -m "chore: Automated build: Update dist folder"
            git push origin Storybook
          fi

  version-tag:
    needs: build
    if: needs.build.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: prepare
        run: | 
          echo "ignore_merge_commits = true" > cog.toml
      - name: Create Version Tag
        id: release
        uses: cocogitto/cocogitto-action@v3
        with:
          release: true
          git-user: 'Cocogitto bot'
          check-latest-tag-only: true
      - name: Generate Changelog
        run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md
      - name: Upload github release
        uses: softprops/action-gh-release@v1
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.release.outputs.version }}